import { existsSync, mkdirSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { chromium } from 'playwright-core'

const root = resolve(import.meta.dirname, '../..')
const credentials = JSON.parse(readFileSync(resolve(root, 'demo-credentials.json'), 'utf8').replace(/^\uFEFF/, ''))
const settings = Object.fromEntries(readFileSync(resolve(root, '.env'), 'utf8').replace(/^\uFEFF/, '').split(/\r?\n/).filter(line => line.includes('=')).map(line => { const index = line.indexOf('='); return [line.slice(0, index), line.slice(index + 1)] }))
const chrome = process.env.PLAYWRIGHT_CHROME || [
  'C:/Program Files/Google/Chrome/Application/chrome.exe',
  'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',
  '/usr/bin/google-chrome',
  '/usr/bin/chromium',
].find(existsSync)
if (!chrome) throw new Error('Chrome/Edge no encontrado; definí PLAYWRIGHT_CHROME.')
const shotDir = resolve(import.meta.dirname, '../.screenshots')
mkdirSync(shotDir, { recursive: true })
const browser = await chromium.launch({ executablePath: chrome, headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 })
try {
  await page.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' })
  await page.getByLabel('Correo electrónico').fill(credentials.customer.email)
  await page.getByLabel('Contraseña').fill(credentials.customer.password)
  await page.getByRole('button', { name: 'Ingresar al observatorio' }).click()
  await page.getByRole('heading', { name: /Buen día/ }).waitFor({ timeout: 15000 })
  await page.getByRole('button', { name: 'Abrir menú de usuario' }).click()
  await page.getByRole('button', { name: 'Mi perfil' }).click()
  await page.getByRole('heading', { name: 'Mi perfil' }).waitFor()
  await page.getByText('Fecha de registro').waitFor()
  await page.getByText(credentials.customer.email).first().waitFor()
  await page.screenshot({ path: resolve(shotDir, 'profile.png'), fullPage: true })
  await page.getByRole('button', { name: 'Abrir menú de usuario' }).click()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Mi perfil' }).waitFor({ state: 'hidden' })
  await page.getByRole('button', { name: 'Resumen', exact: true }).click()
  await page.getByText('Buenos Aires').first().waitFor()
  await page.locator('.trend-card .recharts-area').waitFor()
  await page.screenshot({ path: resolve(shotDir, 'overview.png'), fullPage: true })
  await page.getByRole('button', { name: 'Sensores', exact: true }).click()
  await page.getByRole('heading', { name: 'Sensores alrededor del mundo.' }).waitFor()
  await page.locator('.recent-card tbody tr').first().waitFor()
  await page.screenshot({ path: resolve(shotDir, 'sensors.png'), fullPage: true })
  await page.getByRole('button', { name: 'Informes', exact: true }).click()
  await page.getByRole('heading', { name: 'Informes que dan contexto.' }).waitFor()
  await page.getByRole('button', { name: 'Ver informe' }).first().click()
  await page.locator('.report-modal').waitFor()
  await page.locator('.report-modal').getByRole('button', { name: 'Cerrar', exact: true }).click()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: resolve(shotDir, 'reports.png'), fullPage: true })
  await page.getByRole('button', { name: 'Mensajes', exact: true }).click()
  await page.getByRole('heading', { name: 'Conversaciones que conectan.' }).waitFor()
  await page.screenshot({ path: resolve(shotDir, 'messages.png'), fullPage: true })
  await page.getByRole('button', { name: 'Facturación', exact: true }).click()
  await page.getByRole('heading', { name: 'Facturación y cuenta corriente.' }).waitFor()
  await page.screenshot({ path: resolve(shotDir, 'billing.png'), fullPage: true })
  await page.getByRole('button', { name: 'Acerca de', exact: true }).click()
  await page.getByRole('heading', { name: 'La ciencia detrás de cada dato.' }).waitFor()
  await page.screenshot({ path: resolve(shotDir, 'about.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.waitForFunction(() => document.querySelector('.sidebar').getBoundingClientRect().right <= 0)
  await page.screenshot({ path: resolve(shotDir, 'about-mobile.png'), fullPage: true })
  const mobileOverflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)
  if (mobileOverflow) throw new Error('La página Acerca de desborda horizontalmente en móvil.')
  await page.getByRole('button', { name: 'Abrir menú de usuario' }).click()
  await page.getByRole('button', { name: 'Mi perfil' }).click()
  await page.getByRole('heading', { name: 'Mi perfil' }).waitFor()
  if (await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)) throw new Error('El perfil desborda horizontalmente en móvil.')
  await page.screenshot({ path: resolve(shotDir, 'profile-mobile.png'), fullPage: true })
  await page.getByRole('button', { name: 'Abrir menú', exact: true }).click()
  await page.getByRole('button', { name: 'Sensores', exact: true }).click()
  await page.locator('.recent-card tbody tr').first().waitFor()
  if (await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)) throw new Error('La vista de sensores desborda horizontalmente en móvil.')
  await page.screenshot({ path: resolve(shotDir, 'sensors-mobile.png'), fullPage: true })

  const staffPage = await browser.newPage({ viewport: { width: 1440, height: 900 } })
  await staffPage.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' })
  await staffPage.getByLabel('Correo electrónico').fill(credentials.technician.email)
  await staffPage.getByLabel('Contraseña').fill(credentials.technician.password)
  await staffPage.getByRole('button', { name: 'Ingresar al observatorio' }).click()
  await staffPage.getByRole('button', { name: 'Alertas', exact: true }).click()
  await staffPage.getByRole('heading', { name: 'Alertas y eventos.' }).waitFor()
  await staffPage.locator('.alert-item').first().waitFor()
  await staffPage.screenshot({ path: resolve(shotDir, 'alerts.png'), fullPage: true })

  const adminPage = await browser.newPage({ viewport: { width: 1440, height: 900 } })
  await adminPage.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' })
  await adminPage.getByLabel('Correo electrónico').fill(settings.BOOTSTRAP_ADMIN_EMAIL)
  await adminPage.getByLabel('Contraseña').fill(settings.BOOTSTRAP_ADMIN_PASSWORD)
  await adminPage.getByRole('button', { name: 'Ingresar al observatorio' }).click()
  await adminPage.getByRole('button', { name: 'Usuarios', exact: true }).click()
  await adminPage.getByRole('heading', { name: 'Usuarios y permisos.' }).waitFor()
  const customerRow = adminPage.locator('.user-row').filter({ hasText: credentials.customer.email })
  await customerRow.waitFor()
  const currentRole = await customerRow.getByRole('radio', { checked: true }).textContent()
  const originalRole = currentRole?.includes('Técnico') ? 'Técnico' : currentRole?.includes('Usuario') ? 'Usuario' : null
  if (!originalRole) throw new Error('El cliente de demostración debe tener el rol Usuario o Técnico.')
  const replacementRole = originalRole === 'Usuario' ? 'Técnico' : 'Usuario'
  const originalButton = customerRow.getByRole('radio', { name: originalRole })
  const replacementButton = customerRow.getByRole('radio', { name: replacementRole })
  try {
    await replacementButton.click()
    await customerRow.getByRole('radio', { name: replacementRole, checked: true }).waitFor()
    await customerRow.getByRole('radio', { name: originalRole, checked: false }).waitFor()
  } finally {
    if (await replacementButton.getAttribute('aria-checked') === 'true') {
      await originalButton.click()
      await customerRow.getByRole('radio', { name: originalRole, checked: true }).waitFor()
    }
  }
  await adminPage.screenshot({ path: resolve(shotDir, 'users.png'), fullPage: true })
  await adminPage.getByRole('button', { name: 'Abrir menú de usuario' }).click()
  await adminPage.locator('.account-dropdown').getByRole('button', { name: 'Cerrar sesión' }).click()
  await adminPage.getByRole('heading', { name: 'Ingresá a tu espacio.' }).waitFor()
  console.log('UI smoke passed: perfil, menú de usuario, cierre de sesión, pantallas de cliente y técnico, móvil, y cambio de roles por administrador.')
} finally { await browser.close() }
