import { Activity, ArrowLeft, ArrowRight, BookOpenText, Braces, Cloud, Database, HardDrive, Layers3, LockKeyhole, RadioTower, RefreshCw, ShieldCheck, Waves } from 'lucide-react'
import { Brand, Card, SectionHeading } from '../components'

const stores = [
  { icon: Database, name: 'PostgreSQL', tag: 'DATOS RELACIONALES', color: 'blue', use: 'Usuarios, roles, sensores, solicitudes, ejecuciones, facturas, pagos y cuentas corrientes.', reason: 'Las relaciones, restricciones y transacciones mantienen consistentes los saldos y permisos.' },
  { icon: Waves, name: 'Cassandra', tag: 'SERIES TEMPORALES', color: 'cyan', use: 'Mediciones de temperatura y humedad, organizadas por ciudad, zona o país y por mes.', reason: 'Está preparada para un flujo continuo de escrituras y consultas rápidas por lugar y tiempo.' },
  { icon: Braces, name: 'MongoDB', tag: 'DOCUMENTOS', color: 'green', use: 'Informes generados, alertas y mensajes privados o grupales.', reason: 'Los resultados y mensajes pueden variar de estructura sin exigir tablas rígidas.' },
  { icon: LockKeyhole, name: 'Redis', tag: 'SESIONES', color: 'red', use: 'Tokens de sesiones activas con vencimiento automático.', reason: 'Permite comprobar una sesión de forma rápida; PostgreSQL conserva su historial.' },
]

export default function About({ publicMode = false, onBack }: { publicMode?: boolean; onBack?: () => void }) {
  return <div className={publicMode ? 'public-about' : 'page-content about-page'}>
    {publicMode && <div className="public-about-nav"><Brand /><button className="button button-light" onClick={onBack}><ArrowLeft size={16} /> Volver al acceso</button></div>}
    <SectionHeading eyebrow="ACERCA DE LA PLATAFORMA" title="La ciencia detrás de cada dato." description="Una mirada transparente a las tecnologías que sostienen el observatorio y al recorrido que hace la información." />
    <div className="about-hero">
      <div className="about-hero-copy"><div className="hero-overline"><span className="live-pulse" /> ARQUITECTURA DE DATOS</div><h2>Un planeta en movimiento.<br /><em>Datos que permanecen.</em></h2><p>Cada sensor aporta una pieza del clima global. La plataforma combina cuatro bases especializadas para convertir esas señales en consultas, informes y decisiones trazables.</p></div>
      <div className="about-hero-graphic"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="planet"><span className="planet-meridian" /><span className="planet-equator" /><span className="planet-dot dot-a" /><span className="planet-dot dot-b" /><span className="planet-dot dot-c" /></div><span className="orbit-tag orbit-tag-one">PostgreSQL</span><span className="orbit-tag orbit-tag-two">Cassandra</span><span className="orbit-tag orbit-tag-three">MongoDB</span><span className="orbit-tag orbit-tag-four">Redis</span></div>
    </div>
    <div className="about-intro"><div><span className="eyebrow">01 / LA BASE TECNOLÓGICA</span><h2>Herramientas con un propósito claro.</h2></div><p>El frontend usa <strong>React y TypeScript</strong> para una interfaz segura y mantenible, <strong>Vite</strong> para desarrollo y compilación, y <strong>Recharts</strong> para visualizar mediciones. Una API en <strong>Java 21 y Spring Boot 3</strong> valida permisos y coordina cada operación.</p></div>
    <div className="technology-grid">{stores.map(item => <Card key={item.name} className={`technology-card tech-${item.color}`}><div className="technology-top"><span className="technology-icon"><item.icon size={25} strokeWidth={1.8} /></span><span className="technology-tag">{item.tag}</span></div><h3>{item.name}</h3><p>{item.use}</p><div className="technology-why"><span>POR QUÉ ESTA BASE</span><p>{item.reason}</p></div></Card>)}</div>
    <div className="about-intro"><div><span className="eyebrow">02 / EL RECORRIDO</span><h2>Del sensor a una decisión.</h2></div><p>La API conecta las bases mediante identificadores compartidos. Los datos se guardan en el almacén adecuado para cada uso y los informes conservan el vínculo con su solicitud y ejecución.</p></div>
    <Card className="data-flow-card"><div className="flow-step"><span className="flow-icon"><RadioTower size={23} /></span><strong>Sensor</strong><small>Envía una lectura con su clave</small></div><ArrowRight className="flow-arrow" size={21} /><div className="flow-step"><span className="flow-icon"><Waves size={23} /></span><strong>Cassandra</strong><small>Guarda la serie por lugar y mes</small></div><ArrowRight className="flow-arrow" size={21} /><div className="flow-step"><span className="flow-icon"><Activity size={23} /></span><strong>Proceso</strong><small>Calcula máximos o promedios</small></div><ArrowRight className="flow-arrow" size={21} /><div className="flow-step"><span className="flow-icon"><Braces size={23} /></span><strong>Informe</strong><small>Se conserva en MongoDB</small></div><ArrowRight className="flow-arrow" size={21} /><div className="flow-step"><span className="flow-icon"><Database size={23} /></span><strong>Factura</strong><small>Se registra en PostgreSQL</small></div></Card>
    <div className="about-detail-grid">
      <Card className="about-detail"><span className="detail-icon teal"><HardDrive size={23} /></span><h3>¿Cómo persisten los datos?</h3><p>PostgreSQL, Cassandra y MongoDB escriben en volúmenes propios de Docker. Al reiniciar los contenedores, esos volúmenes permanecen. Los registros no dependen de que la interfaz esté abierta.</p><p>Redis mantiene sesiones temporales: si se vacía, las mediciones, informes y facturas siguen en sus bases; los usuarios simplemente vuelven a iniciar sesión.</p></Card>
      <Card className="about-detail"><span className="detail-icon lilac"><Layers3 size={23} /></span><h3>¿Cómo se relacionan?</h3><p>Una solicitud y su ejecución tienen IDs en PostgreSQL. El informe en MongoDB guarda esos IDs, y las mediciones de Cassandra mantienen el ID de su sensor. La API reúne las piezas y comprueba quién puede ver cada una.</p><p>La facturación se cierra en una transacción SQL para mantener consistente el saldo.</p></Card>
      <Card className="about-detail"><span className="detail-icon peach"><RefreshCw size={23} /></span><h3>¿Qué ocurre si algo falla?</h3><p>No existe una transacción única que abarque todas las bases. Si falla el cierre de una ejecución, la API intenta retirar el informe recién creado y registra la ejecución como fallida para permitir un reintento.</p><p>Las copias de seguridad siguen siendo necesarias para recuperar datos ante una pérdida del equipo o de los volúmenes.</p></Card>
    </div>
    <div className="about-footer-note"><span><ShieldCheck size={19} /> Acceso por roles</span><span><Cloud size={19} /> Datos consultables en línea</span><span><BookOpenText size={19} /> Historial de procesos</span></div>
  </div>
}
